-- Insercao de Produtos
INSERT INTO PRODUTOS (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Notebook Dell XPS', 'Informatica', 4500.00, 6800.00, 15, TRUE);
INSERT INTO PRODUTOS (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Monitor LG 29 Ultrawide', 'Perifericos', 800.00, 1250.00, 42, TRUE);
INSERT INTO PRODUTOS (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Mouse Logitech MX Master 3', 'Perifericos', 350.00, 599.90, 80, TRUE);
INSERT INTO PRODUTOS (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Cadeira Herman Miller Aeron', 'Moveis', 5200.00, 8500.00, 5, TRUE);
INSERT INTO PRODUTOS (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Teclado Mecanico Keychron K2', 'Perifericos', 450.00, 750.00, 30, TRUE);

-- Insercao de Movimentacoes Financeiras (Entradas e Saidas)
INSERT INTO MOVIMENTACOES_FINANCEIRAS (TIPO, VALOR, DATA_MOVIMENTACAO, DESCRICAO, CLIENTE, CATEGORIA, TIPO_PAGAMENTO, QUANTIDADE_PARCELAS, DATA_PRIMEIRO_VENCIMENTO) VALUES ('ENTRADA', 13600.00, CURRENT_DATE(), 'Venda de 2 Notebooks', 'Empresa Horizon', 'Vendas', 'PARCELADO', 4, CURRENT_DATE());
INSERT INTO MOVIMENTACOES_FINANCEIRAS (TIPO, VALOR, DATA_MOVIMENTACAO, DESCRICAO, CLIENTE, CATEGORIA, TIPO_PAGAMENTO, QUANTIDADE_PARCELAS, DATA_PRIMEIRO_VENCIMENTO) VALUES ('SAIDA', 3500.00, CURRENT_DATE(), 'Pagamento de Fornecedor Logitech', 'Fornecedor Logitech', 'Fornecedores', 'AVISTA', 1, CURRENT_DATE());
INSERT INTO MOVIMENTACOES_FINANCEIRAS (TIPO, VALOR, DATA_MOVIMENTACAO, DESCRICAO, CLIENTE, CATEGORIA, TIPO_PAGAMENTO, QUANTIDADE_PARCELAS, DATA_PRIMEIRO_VENCIMENTO) VALUES ('ENTRADA', 1250.00, CURRENT_DATE(), 'Venda 1 Monitor LG', 'Studio Aurora', 'Vendas', 'AVISTA', 1, CURRENT_DATE());
INSERT INTO MOVIMENTACOES_FINANCEIRAS (TIPO, VALOR, DATA_MOVIMENTACAO, DESCRICAO, CLIENTE, CATEGORIA, TIPO_PAGAMENTO, QUANTIDADE_PARCELAS, DATA_PRIMEIRO_VENCIMENTO) VALUES ('SAIDA', 850.00, CURRENT_DATE(), 'Conta de Energia', 'Concessionaria de Energia', 'Despesas Operacionais', 'AVISTA', 1, CURRENT_DATE());
INSERT INTO MOVIMENTACOES_FINANCEIRAS (TIPO, VALOR, DATA_MOVIMENTACAO, DESCRICAO, CLIENTE, CATEGORIA, TIPO_PAGAMENTO, QUANTIDADE_PARCELAS, DATA_PRIMEIRO_VENCIMENTO) VALUES ('ENTRADA', 2250.00, CURRENT_DATE(), 'Venda 3 Teclados Keychron', 'Agencia Polaris', 'Vendas', 'PARCELADO', 3, CURRENT_DATE());
