-- Inserção de Produtos
INSERT INTO PRODUTO (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Notebook Dell XPS', 'Informática', 4500.00, 6800.00, 15, TRUE);
INSERT INTO PRODUTO (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Monitor LG 29 Ultrawide', 'Periféricos', 800.00, 1250.00, 42, TRUE);
INSERT INTO PRODUTO (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Mouse Logitech MX Master 3', 'Periféricos', 350.00, 599.90, 80, TRUE);
INSERT INTO PRODUTO (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Cadeira Herman Miller Aeron', 'Móveis', 5200.00, 8500.00, 5, TRUE);
INSERT INTO PRODUTO (NOME, CATEGORIA, CUSTO, PRECO, ESTOQUE, ATIVO) VALUES ('Teclado Mecânico Keychron K2', 'Periféricos', 450.00, 750.00, 30, TRUE);

-- Inserção de Movimentações Financeiras (Entradas e Saídas)
INSERT INTO MOVIMENTACAO_FINANCEIRA (TIPO, VALOR, DATA, DESCRICAO, CATEGORIA) VALUES ('ENTRADA', 13600.00, CURRENT_DATE(), 'Venda de 2 Notebooks', 'Vendas');
INSERT INTO MOVIMENTACAO_FINANCEIRA (TIPO, VALOR, DATA, DESCRICAO, CATEGORIA) VALUES ('SAIDA', 3500.00, CURRENT_DATE(), 'Pagamento de Fornecedor Logitech', 'Fornecedores');
INSERT INTO MOVIMENTACAO_FINANCEIRA (TIPO, VALOR, DATA, DESCRICAO, CATEGORIA) VALUES ('ENTRADA', 1250.00, CURRENT_DATE(), 'Venda 1 Monitor LG', 'Vendas');
INSERT INTO MOVIMENTACAO_FINANCEIRA (TIPO, VALOR, DATA, DESCRICAO, CATEGORIA) VALUES ('SAIDA', 850.00, CURRENT_DATE(), 'Conta de Energia', 'Despesas Operacionais');
INSERT INTO MOVIMENTACAO_FINANCEIRA (TIPO, VALOR, DATA, DESCRICAO, CATEGORIA) VALUES ('ENTRADA', 2250.00, CURRENT_DATE(), 'Venda 3 Teclados Keychron', 'Vendas');
